"""
Workflow slot definitions — every enterprise workflow type.

Each entry defines:
  - label:          Human-readable name for the workflow
  - department:     Which dept handles it (HR / Finance / IT)
  - required_slots: Must be collected before the workflow can be created
  - optional_slots: Nice-to-have; requested but not blocking
  - slot_prompts:   Short English description of each slot (used in
                    clarification questions generated by the LLM)
  - approvers:      Who in the approval chain gets notified
  - sla:            Expected response time shown to the requester
  - action_type:    Maps to the DB action_type enum value
"""
from __future__ import annotations

WORKFLOW_DEFINITIONS: dict[str, dict] = {

    # ── HR ────────────────────────────────────────────────────────────────────

    "apply_leave": {
        "label": "Leave Request",
        "department": "HR",
        "required_slots": ["leave_type", "start_date", "end_date_or_days"],
        "optional_slots": ["reason"],
        "slot_prompts": {
            "leave_type": "type of leave (Annual / Emergency / Personal / Study)",
            "start_date": "leave start date",
            "end_date_or_days": "return date or number of days",
            "reason": "reason for the leave",
        },
        "approvers": "your direct manager",
        "sla": "1–2 business days",
        "action_type": "apply_leave",
    },

    "sick_leave_report": {
        "label": "Sick Leave Report",
        "department": "HR",
        "required_slots": ["days"],
        "optional_slots": ["medical_cert_available"],
        "slot_prompts": {
            "days": "how many days you'll be absent",
            "medical_cert_available": "whether you have a medical certificate (required if 4+ days)",
        },
        "approvers": "your manager is notified automatically",
        "sla": "immediate notification",
        "action_type": "sick_leave_report",
    },

    "maternity_leave_request": {
        "label": "Maternity / Parental Leave Request",
        "department": "HR",
        "required_slots": ["start_date"],
        "optional_slots": ["expected_duration", "medical_cert"],
        "slot_prompts": {
            "start_date": "planned leave start date",
            "expected_duration": "expected duration (default: 90 days full pay)",
            "medical_cert": "whether you have a doctor's letter confirming the due date",
        },
        "approvers": "manager + HR",
        "sla": "HR acknowledges within 2 business days",
        "action_type": "maternity_leave_request",
    },

    "wfh_request": {
        "label": "Work From Home Request",
        "department": "HR",
        "required_slots": ["wfh_date"],
        "optional_slots": ["reason"],
        "slot_prompts": {
            "wfh_date": "the date(s) you need to work from home",
            "reason": "reason for WFH (optional)",
        },
        "approvers": "your manager",
        "sla": "1 business day",
        "action_type": "wfh_request",
    },

    "grievance_report": {
        "label": "Grievance / Complaint",
        "department": "HR",
        "required_slots": ["issue_type", "description"],
        "optional_slots": ["preferred_resolution"],
        "slot_prompts": {
            "issue_type": "type of issue (Harassment / Discrimination / Unfair treatment / Other)",
            "description": "brief description of the situation",
            "preferred_resolution": "preferred outcome (optional)",
        },
        "approvers": "HR Employee Relations (confidential)",
        "sla": "acknowledged within 2 days, resolved within 15 business days",
        "action_type": "grievance_report",
    },

    "training_request": {
        "label": "Training Request",
        "department": "HR",
        "required_slots": ["course_name", "justification"],
        "optional_slots": ["estimated_cost", "provider"],
        "slot_prompts": {
            "course_name": "name of the training or course",
            "justification": "how this training benefits your role",
            "estimated_cost": "estimated cost in AED (optional)",
            "provider": "training provider name (optional)",
        },
        "approvers": "manager → HR → Finance (if >AED 5,000)",
        "sla": "3–5 business days",
        "action_type": "training_request",
    },

    "update_profile": {
        "label": "Profile Update Request",
        "department": "HR",
        "required_slots": ["field_to_update", "new_value"],
        "optional_slots": [],
        "slot_prompts": {
            "field_to_update": "which field to update (e.g., phone, address, bank details)",
            "new_value": "the new value",
        },
        "approvers": "HR processes within 2 business days",
        "sla": "2 business days",
        "action_type": "update_profile",
    },

    # ── Finance ───────────────────────────────────────────────────────────────

    "salary_increase_request": {
        "label": "Salary Increase Request",
        "department": "Finance",
        "required_slots": ["justification"],
        "optional_slots": ["desired_percentage", "effective_date"],
        "slot_prompts": {
            "justification": "your justification for the increase (performance, market rate, expanded role, etc.)",
            "desired_percentage": "percentage increase requested (optional — e.g., 10%)",
            "effective_date": "when you'd like this effective (optional — defaults to next review cycle)",
        },
        "approvers": "manager → HR → Finance Director",
        "sla": "10–15 business days",
        "action_type": "salary_increase_request",
    },

    "submit_expense": {
        "label": "Expense Claim",
        "department": "Finance",
        "required_slots": ["amount", "category", "expense_date"],
        "optional_slots": ["description"],
        "slot_prompts": {
            "amount": "total amount with currency (e.g., AED 250)",
            "category": "expense category (Client meal / Taxi / Stationery / Training / Other)",
            "expense_date": "date the expense was incurred",
            "description": "brief description (optional)",
        },
        "approvers": "manager → Finance",
        "sla": "5–7 business days reimbursement after approval",
        "action_type": "submit_expense",
    },

    "request_advance": {
        "label": "Salary Advance Request",
        "department": "Finance",
        "required_slots": ["amount", "reason"],
        "optional_slots": ["repayment_months"],
        "slot_prompts": {
            "amount": "advance amount needed in AED (max 50% of monthly basic)",
            "reason": "reason for the advance (medical emergency, family matter, etc.)",
            "repayment_months": "preferred repayment period in months (standard: 3 months)",
        },
        "approvers": "manager → HR → Finance",
        "sla": "3–5 business days",
        "action_type": "request_advance",
    },

    # ── IT ────────────────────────────────────────────────────────────────────

    "it_ticket": {
        "label": "IT Support Ticket",
        "department": "IT",
        "required_slots": ["issue_type", "description"],
        "optional_slots": ["urgency"],
        "slot_prompts": {
            "issue_type": "type of issue (Hardware / Software / Access / Network / Security)",
            "description": "brief description of the problem",
            "urgency": "urgency level (Low / Medium / High / Critical)",
        },
        "approvers": "IT Support team",
        "sla": "Critical: 2h | High: 4h | Medium: 1 day | Low: 3 days",
        "action_type": "it_ticket",
    },

    "request_access": {
        "label": "System Access Request",
        "department": "IT",
        "required_slots": ["system_name", "access_type"],
        "optional_slots": ["business_justification"],
        "slot_prompts": {
            "system_name": "which system or application you need access to",
            "access_type": "level of access needed (Read / Write / Admin)",
            "business_justification": "business reason for needing access (optional)",
        },
        "approvers": "manager → IT Security",
        "sla": "1–3 business days",
        "action_type": "request_access",
    },
}


def get_workflow_def(workflow_type: str) -> dict:
    """Return the full definition for a workflow type, or empty dict if unknown."""
    return WORKFLOW_DEFINITIONS.get(workflow_type, {})


def get_required_slots(workflow_type: str) -> list[str]:
    return WORKFLOW_DEFINITIONS.get(workflow_type, {}).get("required_slots", [])


def get_missing_slots(workflow_type: str, collected: dict) -> list[str]:
    """Return list of required slots not yet collected."""
    required = get_required_slots(workflow_type)
    return [s for s in required if not collected.get(s)]


def get_action_type(workflow_type: str) -> str:
    """Return the DB action_type string for a workflow type."""
    return WORKFLOW_DEFINITIONS.get(workflow_type, {}).get("action_type", workflow_type)


def all_workflow_labels() -> str:
    """Return a human-readable comma-separated list of all workflow types."""
    return ", ".join(
        f"{v['label']} ({k})" for k, v in WORKFLOW_DEFINITIONS.items()
    )
